### ISSUE TITLE
Error with 850i

### ISSUE THREAD

**Issue by fusionstream** [notaz/corsairmi#1]
I get this error with my RMi 850 ----> unexpected device: 1997:2433

**Comment by notaz** [comment]
If you comment out [line 209](https://github.com/notaz/corsairmi/blob/master/corsairmi.c#L209), does it show sane info?

**Comment by notaz** [comment]
Hmm wait, 1997:2433 looks to be your keyboard:
https://usb-ids.gowdy.us/read/UD/1997/2433

You should better check lsusb to see it your device enumerates at all, then use different /dev/hidrawX node.

**Comment by fusionstream** [comment]
~~Now I get:
unexpected device: 413c:2106
which is odd since that is the same keyboard I used then. I shoulda run lsusb then huh.
(Edit: As in I just ran lsusb and 413c:2106 is my keyboard)~~
Edit: Edit: Ignore that. It isn't detecting my other keyboard is what is happening now.

Anyway mine was under hidraw1. Changed the code and compiled (and it works). Anyway to make it autodetect?
Edit: Edit: Edit: So I just saw on the main page that you can pass parameters to the program to choose the device. Silly me. Still though... Anyway to make it autodetect? Also, is your inbox full now? :x grr

**Comment by notaz** [comment]
You haven't told me what USB ID of your PSU is.
Also what do you mean by my inbox is full? What inbox?

**Comment by fusionstream** [comment]
Well you didn't ask for my usb id. 
1b1c:1c0c

**Comment by notaz** [comment]
Pushed support with autodetection, does it work?

**Comment by fusionstream** [comment]
Yes sir. Thanks.
