### ISSUE TITLE
License inclusion

### ISSUE THREAD

**Issue by realies** [notaz/corsairmi#10]
I am distributing the `corsairmi` binary as part of the [`corsairpsu-unraid`](https://github.com/realies/corsairpsu-unraid) unRAID plugin. I have linked this repository from within the README file, but does it suffice the license under which it is published?

**Comment by notaz** [comment]
It's standard 3-clause BSD, from how I understand it you need to have the license text reproduced somewhere within your package, can be in some file where you already have similar info or a separate file like LICENSE-corsairmi.

**Comment by realies** [comment]
Thanks for the clarification, I have force pushed an update to the repository to include a `LICENSE-corsairmi` file and a change to the package creating script that includes license files in every instance.
